name: Linux Compiler Testing

on: [push, pull_request]

env:
  SCCACHE_DIR: ${{ github.workspace }}/.cache/sccache

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - g++-8
          - g++-9
          - g++-10
          - clang++-8
          - clang++-9
          - clang++-10
        build_type: [Debug, Release]

    runs-on: ubuntu-20.04

    env:
      CXX: ${{ matrix.compiler }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Cache dependencies
      uses: actions/cache@v2
      env:
        cache-name: cache-deps
      with:
        path: .cache/deps
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/ThirdPartyDeps.cmake') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Cache build
      uses: actions/cache@v2
      env:
        cache-name: cache-build
      with:
        path: .cache/sccache
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Install sccache
      run: |
        curl -SL https://github.com/mozilla/sccache/releases/download/v0.2.15/sccache-v0.2.15-x86_64-unknown-linux-musl.tar.gz | tar xvz --strip-components=1 --wildcards "*/sccache"
        chmod +x sccache
    - run: cmake -E make_directory build

    - working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - working-directory: build/
      run: cmake --build .

    - working-directory: build/
      run: ctest --output-on-failure

